
let spriteGraphics = {
  virus :     require("../assets/sprites/virus_dark.png"),
  syringe_left: require("../assets/sprites/syringe_left.png"),
  syringe_right: require("../assets/sprites/syringe_right.png"),
  syringe_up: require("../assets/sprites/syringe_up.png"),
  syringe_down: require("../assets/sprites/syringe_down.png"),
  explosion_0 : require("../assets/sprites/explosion_0.png"),
  explosion_1 : require("../assets/sprites/explosion_1.png"),
  explosion_2 : require("../assets/sprites/explosion_2.png"),
  explosion_3 : require("../assets/sprites/explosion_3.png"),
  explosion_4 : require("../assets/sprites/explosion_4.png"),
  explosion_5 : require("../assets/sprites/explosion_5.png"),
  explosion_6 : require("../assets/sprites/explosion_6.png"),

  globeTrotter_left_0 : require("../assets/sprites/globaltrotter_left_0.png"),
  globeTrotter_left_1 : require("../assets/sprites/globaltrotter_left_1.png"),
  globeTrotter_left_2 : require("../assets/sprites/globaltrotter_left_2.png"),
  globeTrotter_left_3 : require("../assets/sprites/globaltrotter_left_3.png"),
  globeTrotter_left_4 : require("../assets/sprites/globaltrotter_left_4.png"),
  globeTrotter_left_5 : require("../assets/sprites/globaltrotter_left_5.png"),
  globeTrotter_left_6 : require("../assets/sprites/globaltrotter_left_6.png"),
  globeTrotter_left_7 : require("../assets/sprites/globaltrotter_left_7.png"),
  globeTrotter_left_8 : require("../assets/sprites/globaltrotter_left_8.png"),
  globeTrotter_left_9 : require("../assets/sprites/globaltrotter_left_9.png"),
  globeTrotter_left_10 : require("../assets/sprites/globaltrotter_left_10.png"),
  globeTrotter_left_11 : require("../assets/sprites/globaltrotter_left_11.png"),
  globeTrotter_left_12 : require("../assets/sprites/globaltrotter_left_12.png"),
  globeTrotter_left_13 : require("../assets/sprites/globaltrotter_left_13.png"),
  globeTrotter_left_14 : require("../assets/sprites/globaltrotter_left_14.png"),
  globeTrotter_left_15 : require("../assets/sprites/globaltrotter_left_15.png"),

  globeTrotter_right_0 : require("../assets/sprites/globaltrotter_right_0.png"),
  globeTrotter_right_1 : require("../assets/sprites/globaltrotter_right_1.png"),
  globeTrotter_right_2 : require("../assets/sprites/globaltrotter_right_2.png"),
  globeTrotter_right_3 : require("../assets/sprites/globaltrotter_right_3.png"),
  globeTrotter_right_4 : require("../assets/sprites/globaltrotter_right_4.png"),
  globeTrotter_right_5 : require("../assets/sprites/globaltrotter_right_5.png"),
  globeTrotter_right_6 : require("../assets/sprites/globaltrotter_right_6.png"),
  globeTrotter_right_7 : require("../assets/sprites/globaltrotter_right_7.png"),
  globeTrotter_right_8 : require("../assets/sprites/globaltrotter_right_8.png"),
  globeTrotter_right_9 : require("../assets/sprites/globaltrotter_right_9.png"),
  globeTrotter_right_10 : require("../assets/sprites/globaltrotter_right_10.png"),
  globeTrotter_right_11 : require("../assets/sprites/globaltrotter_right_11.png"),
  globeTrotter_right_12 : require("../assets/sprites/globaltrotter_right_12.png"),
  globeTrotter_right_13 : require("../assets/sprites/globaltrotter_right_13.png"),
  globeTrotter_right_14 : require("../assets/sprites/globaltrotter_right_14.png"),
  globeTrotter_right_15 : require("../assets/sprites/globaltrotter_right_15.png"),  

  globeTrotter_up_0 : require("../assets/sprites/globaltrotter_up_0.png"),
  globeTrotter_up_1 : require("../assets/sprites/globaltrotter_up_1.png"),
  globeTrotter_up_2 : require("../assets/sprites/globaltrotter_up_2.png"),
  globeTrotter_up_3 : require("../assets/sprites/globaltrotter_up_3.png"),
  globeTrotter_up_4 : require("../assets/sprites/globaltrotter_up_4.png"),
  globeTrotter_up_5 : require("../assets/sprites/globaltrotter_up_5.png"),
  globeTrotter_up_6 : require("../assets/sprites/globaltrotter_up_6.png"),
  globeTrotter_up_7 : require("../assets/sprites/globaltrotter_up_7.png"),
  globeTrotter_up_8 : require("../assets/sprites/globaltrotter_up_8.png"),
  globeTrotter_up_9 : require("../assets/sprites/globaltrotter_up_9.png"),
  globeTrotter_up_10 : require("../assets/sprites/globaltrotter_up_10.png"),
  globeTrotter_up_11 : require("../assets/sprites/globaltrotter_up_11.png"),
  globeTrotter_up_12 : require("../assets/sprites/globaltrotter_up_12.png"),
  globeTrotter_up_13 : require("../assets/sprites/globaltrotter_up_13.png"),
  globeTrotter_up_14 : require("../assets/sprites/globaltrotter_up_14.png"),
  globeTrotter_up_15 : require("../assets/sprites/globaltrotter_up_15.png"),
  
  globeTrotter_down_0 : require("../assets/sprites/globaltrotter_down_0.png"),
  globeTrotter_down_1 : require("../assets/sprites/globaltrotter_down_1.png"),
  globeTrotter_down_2 : require("../assets/sprites/globaltrotter_down_2.png"),
  globeTrotter_down_3 : require("../assets/sprites/globaltrotter_down_3.png"),
  globeTrotter_down_4 : require("../assets/sprites/globaltrotter_down_4.png"),
  globeTrotter_down_5 : require("../assets/sprites/globaltrotter_down_5.png"),
  globeTrotter_down_6 : require("../assets/sprites/globaltrotter_down_6.png"),
  globeTrotter_down_7 : require("../assets/sprites/globaltrotter_down_7.png"),
  globeTrotter_down_8 : require("../assets/sprites/globaltrotter_down_8.png"),
  globeTrotter_down_9 : require("../assets/sprites/globaltrotter_down_9.png"),
  globeTrotter_down_10 : require("../assets/sprites/globaltrotter_down_10.png"),
  globeTrotter_down_11 : require("../assets/sprites/globaltrotter_down_11.png"),
  globeTrotter_down_12 : require("../assets/sprites/globaltrotter_down_12.png"),
  globeTrotter_down_13 : require("../assets/sprites/globaltrotter_down_13.png"),
  globeTrotter_down_14 : require("../assets/sprites/globaltrotter_down_14.png"),
  globeTrotter_down_15 : require("../assets/sprites/globaltrotter_down_15.png")  
};

export default spriteGraphics;