
let spriteData =
{
virus: { left: ['virus'], right: ['virus'], up: ['virus'], down: ['virus'],
 weapon: false, pickup: false, deadly: true, hitpoints: 5, speed: 2, score: 10},
syringe: { left: ['syringe_left'], right: ['syringe_right'], up: ['syringe_up'], down: ['syringe_down'],
 weapon: true, pickup: false, deadly: true, hitpoints: 2, speed: 4, score: 0},
explosion: { left: ['explosion_0', 'explosion_1', 'explosion_2', 'explosion_3', 'explosion_4', 'explosion_5', 'explosion_6'],
right: ['explosion_0', 'explosion_1', 'explosion_2', 'explosion_3', 'explosion_4', 'explosion_5', 'explosion_6'],
up: ['explosion_0', 'explosion_1', 'explosion_2', 'explosion_3', 'explosion_4', 'explosion_5', 'explosion_6'],
down: ['explosion_0', 'explosion_1', 'explosion_2', 'explosion_3', 'explosion_4', 'explosion_5', 'explosion_6'],
  weapon: false, pickup: false, deadly: false, hitpoints: 0, speed: 0, score: 0},
player: { left: [
  'globeTrotter_left_0',
  'globeTrotter_left_1',
  'globeTrotter_left_2',
  'globeTrotter_left_3',
  'globeTrotter_left_4',
  'globeTrotter_left_5',
  'globeTrotter_left_6',
  'globeTrotter_left_7',
  'globeTrotter_left_8',
  'globeTrotter_left_9',
  'globeTrotter_left_10',
  'globeTrotter_left_11',
  'globeTrotter_left_12',
  'globeTrotter_left_13',
  'globeTrotter_left_14',
  'globeTrotter_left_15',    
],
right: [
  'globeTrotter_right_0',
  'globeTrotter_right_1',
  'globeTrotter_right_2',
  'globeTrotter_right_3',
  'globeTrotter_right_4',
  'globeTrotter_right_5',
  'globeTrotter_right_6',
  'globeTrotter_right_7',
  'globeTrotter_right_8',
  'globeTrotter_right_9',
  'globeTrotter_right_10',
  'globeTrotter_right_11',
  'globeTrotter_right_12',
  'globeTrotter_right_13',
  'globeTrotter_right_14',
  'globeTrotter_right_15',    
],
up: [
  'globeTrotter_up_0',
  'globeTrotter_up_1',
  'globeTrotter_up_2',
  'globeTrotter_up_3',
  'globeTrotter_up_4',
  'globeTrotter_up_5',
  'globeTrotter_up_6',
  'globeTrotter_up_7',
  'globeTrotter_up_8',
  'globeTrotter_up_9',
  'globeTrotter_up_10',
  'globeTrotter_up_11',
  'globeTrotter_up_12',
  'globeTrotter_up_13',
  'globeTrotter_up_14',
  'globeTrotter_up_15',    
],
down: [
  'globeTrotter_down_0',
  'globeTrotter_down_1',
  'globeTrotter_down_2',
  'globeTrotter_down_3',
  'globeTrotter_down_4',
  'globeTrotter_down_5',
  'globeTrotter_down_6',
  'globeTrotter_down_7',
  'globeTrotter_down_8',
  'globeTrotter_down_9',
  'globeTrotter_down_10',
  'globeTrotter_down_11',
  'globeTrotter_down_12',
  'globeTrotter_down_13',
  'globeTrotter_down_14',
  'globeTrotter_down_15',    
],
 weapon: false, pickup: false, deadly: false, hitpoints: 20, speed: 2, score: 0}

};

export default spriteData;