
let spriteData =
{
virus: { left: ['virus'], right: ['virus'], up: ['virus'], down: ['virus'],
 weapon: false, pickup: false, deadly: true, hitpoints: 5, speed: 2},
syringe: { left: ['syringe_left'], right: ['syringe_right'], up: ['syringe_up'], down: ['syringe_douwb'],
 weapon: false, pickup: false, deadly: true, hitpoints: 2, speed: 4},
player: { left: [
  'globalTrotter_left_0',
  'globalTrotter_left_1',
  'globalTrotter_left_2',
  'globalTrotter_left_3',
  'globalTrotter_left_4',
  'globalTrotter_left_5',
  'globalTrotter_left_6',
  'globalTrotter_left_7',
  'globalTrotter_left_8',
  'globalTrotter_left_9',
  'globalTrotter_left_10',
  'globalTrotter_left_11',
  'globalTrotter_left_12',
  'globalTrotter_left_13',
  'globalTrotter_left_14',
  'globalTrotter_left_15',    
],
right: [
  'globalTrotter_right_0',
  'globalTrotter_right_1',
  'globalTrotter_right_2',
  'globalTrotter_right_3',
  'globalTrotter_right_4',
  'globalTrotter_right_5',
  'globalTrotter_right_6',
  'globalTrotter_right_7',
  'globalTrotter_right_8',
  'globalTrotter_right_9',
  'globalTrotter_right_10',
  'globalTrotter_right_11',
  'globalTrotter_right_12',
  'globalTrotter_right_13',
  'globalTrotter_right_14',
  'globalTrotter_right_15',    
],
up: [
  'globalTrotter_up_0',
  'globalTrotter_up_1',
  'globalTrotter_up_2',
  'globalTrotter_up_3',
  'globalTrotter_up_4',
  'globalTrotter_up_5',
  'globalTrotter_up_6',
  'globalTrotter_up_7',
  'globalTrotter_up_8',
  'globalTrotter_up_9',
  'globalTrotter_up_10',
  'globalTrotter_up_11',
  'globalTrotter_up_12',
  'globalTrotter_up_13',
  'globalTrotter_up_14',
  'globalTrotter_up_15',    
],
down: [
  'globalTrotter_down_0',
  'globalTrotter_down_1',
  'globalTrotter_down_2',
  'globalTrotter_down_3',
  'globalTrotter_down_4',
  'globalTrotter_down_5',
  'globalTrotter_down_6',
  'globalTrotter_down_7',
  'globalTrotter_down_8',
  'globalTrotter_down_9',
  'globalTrotter_down_10',
  'globalTrotter_down_11',
  'globalTrotter_down_12',
  'globalTrotter_down_13',
  'globalTrotter_down_14',
  'globalTrotter_down_15',    
],
 weapon: false, pickup: false, deadly: false, hitpoints: 20, speed: 2}

};

export default spriteData;